version: '3.0'

services:
  neo4j:
    image: neo4j:latest
    container_name: dsi_social_network
    ports: 
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      NEO4J_AUTH: 'neo4j/password' # username/password